name: Multi-Project Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-learn-serde:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build learn-serde
      run: |
        cd learn-serde
        cargo build --verbose

  build-project-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project-1
      run: |
        cd project-1
        cargo build --verbose

  build-project-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project-2
      run: |
        cd project-2
        cargo build --verbose

  build-project-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project-3
      run: |
        cd project-3
        cargo build --verbose

  build-project-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project-4
      run: |
        cd project-4
        cargo build --verbose

  build-project-5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project-5
      run: |
        cd project-5
        cargo build --verbose